== The story behind this solution pattern

Travelz is a fictitious travel booking company. The team has built their application using microservices architecture and and the portal runs on Red Hat OpenShift. 

The Travelz application has two business units responsible for different aspects of the travel booking system. 

* The _travel-portal_  business unit is responsible for several travel shops, where users can search for and book flights, hotels, cars or insurance.
* The _travel-agency_  business unit host a set of services created to provide quotes for travel.

With the growing number of microservices, the team needed a way to manage, secure and control how the services talk to each other. Service Mesh is identified as great fit for this purpose

As the company grew, they plan to share their APIs with other internal LOBs and external partners. The internal and external clients' applications would need to access data and booking related information from Travelz microservices in the form of APIs. The Engineering teams now needed to ensure that they give secure access to their APIs externally and also manage and monitor the usage of these APIs to make sure everything is in line with the business agreements put in place.

_Travelz_ would like to allow for travel aggregators to be able display flights, hotels insurance cars details. They would like to track any calls from these external clients and partners so as to identify the traffic generated by those teams. This would allow _Travelz_ to be able to reward the partners based on the traffic. They would also these external partners to be able to sign up for services by themselves 

=== Introducing new requirements
Below are the set of key requirements for the development teams to tackle:

* Leverage Service Mesh for Intra Domain or East-West communication
* Ensure a secure and standardized communication across microservices
* Share APIs securely with other orgs or external partners and monitor them - Inter Domain or North-South
* Launch a new version of a service and move it to deployment in Canary style


== Technical Overview

To connect, manage and observe the microservices,  and control traffic between service-to-service, Travelz decided to adopt Istio based service mesh. +
With  Red Hat OpenShift Service Mesh, the team was able to provides the necessary service-to-service capabilities — traffic monitoring, access control, discovery, security, resiliency, metrics, and more — without requiring changes to the code of any of the app's microservices.

With the introduction of external clients, there is a need to allow access of these services by other partners, clients and even other BUs. 
Red Hat® 3scale API Management makes it easy to manage, share, publish, secure and monetize these services as APIs.

The Red Hat 3scale Istio plugin can connect with Red Hat 3scale API management to authorize API requests and report use. This integration allows you to efficiently set up an API with a service mesh backend.