= Solution Patterns: A comprehensive service architecture API Management and Service Meh
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book

API-centric and microservices-based IT architectures improve speed, agility, and efficiency. Consistent and effective management of these interfaces and services is critical for successful deployment and use. Most organizations look for either an API management or a service mesh solution to accomplish this. Determining which approaches and tools to use within your organization can be confusing. However these two technologies are actually complementary and can be used together to deliver a complete service management architecture. 

This solution pattern helps you understand how to use these solutions together to setup a comprehensive service management architecture.

:sectnums:


include::content-overview.adoc[]

[#use-cases]
== Use cases


App modernization resulting in cloud-native technologies need a way to manage their services. Service mesh provides well defined management of service-service communication. 

Organizations are implementing strategies to manage their APIs so they can respond to rapid changes in customer demands.  An API management solution allows  secure access to their services and APIs, so that the internal teams and external partners and clients can access these APIs in structured way.

As you can see, organizations have a need for both of these technologies. 

Red Hat OpenShift Service Mesh and Red Hat 3scale API  Management make it easy for these solutions to work with each other to help organizations build a comprehensive services archiecture

Some of the benefits are

* increased observability and tracing across the services, standardize the security across services so that dev teams can manage  microservices more easily
* formalizing inter-service communication in large corporate networks with api contracts
* provide access to external partners, clients and developers who want to build value added services on top of existing offering. Build a self sign up workflow o obtain credentials, add usage limits to the API based on the business contract and monitor the usage by the external clients.
* enable secure access to apps outside the service mesh
* intelligent traffic routing to the services and APIs based on the application accessing them

.A quick refresher
[cols="1,1"]
|===
| API Management | Service Mesh

| (a) manages relationship between service (API) providers and service consumers  |  (a) delivers advanced traffic control, security, resilience and observability for cloud-native apps


| (b) securely exposes  services to external clients or other Business Unit within the same enterprise (also called _North-South_ or Inter Domain) | (b) enables the standardization across the service interactions  (also called _East-West_ or Intra domain)


| (c) ideal for teams that want to deliver services beyond their domain to other internal groups or external users. | (c) ideal for development teams that need to access services through network interfaces and protocols.

|===

include::01-pattern.adoc[]
